version: '3.9'

services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      #- static-data:/vol/web
      - /vol/web:/vol/web

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      #- static-data:/vol/static
      - /vol/web:/vol/web
      - ssl-certs:/etc/letsencrypt/live/api.digitaleasy.cl
    environment:
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASSWORD}
  db:
    image: mysql:8.0.29
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASSWORD}
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
volumes:
  #static-data:
  ssl-certs:
  mysql-data: