# Generated by Django 4.0.5 on 2022-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ig_account', models.CharField(max_length=60)),
                ('goals', models.TextField(max_length=300)),
                ('creation_year', models.CharField(max_length=4, null=True)),
            ],
            options={
                'db_table': 'client_business',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=35, null=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
