# Generated by Django 4.0.5 on 2022-07-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_client_name_client_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='clients',
            new_name='client',
        ),
    ]
