# Generated by Django 4.0.5 on 2022-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_clients_business_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='creation_year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
