# Generated by Django 4.0.5 on 2022-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClientData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('business_category', models.CharField(blank=True, max_length=255, null=True)),
                ('business_creation_year', models.CharField(blank=True, max_length=255, null=True)),
                ('business_goals', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ig_account', models.CharField(blank=True, max_length=255, null=True)),
                ('more_details', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'new_client_data',
            },
        ),
        migrations.DeleteModel(
            name='NewClient',
        ),
    ]
