# Generated by Django 4.0.5 on 2022-06-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorders',
            old_name='service_id',
            new_name='service',
        ),
    ]
