# Generated by Django 4.0.5 on 2022-07-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
