# Generated by Django 4.0.5 on 2022-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorders',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
