# Generated by Django 4.0.5 on 2022-07-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_client_name_client_email_and_more'),
        ('payments', '0002_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorders',
            name='business',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='clients.business'),
            preserve_default=False,
        ),
    ]
