# Generated by Django 4.0.5 on 2022-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_serviceorders_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorders',
            old_name='date',
            new_name='request_date',
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
    ]
