# Generated by Django 4.0.5 on 2022-07-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=26)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'custom_service',
            },
        ),
        ##migrations.AddField(
         #   model_name='serviceorders',
         #   name='custom_service',
         #   field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='payments.customservice'),
         #   preserve_default=False,
        #),
    ]
