# Generated by Django 4.0.5 on 2022-06-30 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_client_user_alter_service_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='customer_name',
            new_name='client_name',
        ),
    ]
