# Generated by Django 4.0.5 on 2022-07-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_date_serviceorders_request_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorders',
            old_name='purchase_date',
            new_name='first_purchase_date',
        ),
        migrations.RemoveField(
            model_name='serviceorders',
            name='active',
        ),
        migrations.RemoveField(
            model_name='serviceorders',
            name='approved',
        ),
        migrations.AddField(
            model_name='service',
            name='plan_duration_months',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='last_purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='status',
            field=models.CharField(choices=[('NP', 'No procesado'), ('A', 'Activo'), ('I', 'Inactivo')], default='NP', max_length=3),
            preserve_default=False,
        ),
    ]
