# Generated by Django 4.0.5 on 2022-07-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_business_creation_year'),
        ('payments', '0003_serviceorders_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorders',
            name='business',
        ),
        migrations.AddField(
            model_name='serviceorders',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clients.client'),
            preserve_default=False,
        ),
    ]
