# Generated by Django 4.0.5 on 2022-07-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_customservice_serviceorders_custom_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customservice',
            name='token',
            field=models.CharField(max_length=40),
        ),
    ]
