# Generated by Django 4.0.5 on 2022-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_customservice_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customservice',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
