# Generated by Django 4.0.5 on 2022-07-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_customservice_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorders',
            name='custom_service',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.PROTECT, to='payments.customservice'),
            preserve_default=False,
        ),
    ]
