# Generated by Django 4.0.5 on 2022-07-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_serviceorders_custom_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorders',
            name='custom_service',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='payments.customservice'),
            preserve_default=False,
        ),
    ]
