# Generated by Django 4.0.5 on 2022-07-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_serviceorders_custom_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorders',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.service'),
        ),
    ]
