# Generated by Django 4.0.5 on 2022-07-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_serviceorders_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorders',
            name='custom_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.customservice'),
        ),
    ]
